### ISSUE TITLE
Rules which may never fire

### ISSUE THREAD

**Issue by pmlodawski** [Gabriel439/Haskell-Pipes-Library#124]
Hello!
There are some warnings about rules which may never fire when compiling pipes with ghc-7.8.2. 
I think that fixing them is important. Here is install log http://lpaste.net/109551

**Comment by bgamari** [comment]
It may be that this was fixed in #163.

**Comment by Gabriel439** [comment]
So there was one warning left related to `_bind` but I fixed it in c366c26a01689527830336250aef98762390c304 by adding a `{-# NOINLINE [1] _bind #-}` pragma and I verified that this gives **exactly** the same performance as the original version (literally indistinguishable).

Now that all warnings related to rule firings are fixed this issue is finally resolved.

**Comment by Gabriel439** [comment]
Whoops!  I pushed that commit to the wrong branch.  The fix on master is 96c57a4fc639ef35c2ba8962ff5d404ac35583e8
